### ISSUE TITLE
What's the font face used on screenshot?

### ISSUE THREAD

**Issue by richellyitalo** [jpinnix/railscast#5]
Please, what's the font face used on screenshot?

**Comment by jpinnix** [comment]
The typeface is [Hack](http://sourcefoundry.org/hack). Sometimes, I use [Operator](https://www.typography.com/fonts/operator/styles/operatormonoscreensmart), but it is expensive.

**Comment by richellyitalo** [comment]
Thanks!

**Comment by jpinnix** [comment]
My pleasure!
